@hostname = localhost
@port = 3002
@host = {{hostname}}:{{port}}

###

# Get all blog posts
# @name posts
GET http://{{host}}/api/posts?sortDirection=desc&sortProperty=createdBy&page=1 HTTP/1.1

###

@first_post = {{posts.response.body.$.entities[0].id}}
@first_post_user = {{posts.response.body.$.entities[0].userId}}

###

# Get categories into variable
# @name categories

GET http://{{host}}/api/categories/ HTTP/1.1

###

@first_category = {{categories.response.body.$[0].id}}

# Get all blog posts of first category from previous request

GET http://{{host}}/api/posts?categories={{first_category}}&sortDirection=desc&sortProperty=createdBy&page=1 HTTP/1.1

###

PATCH http://{{host}}/api/posts/{{first_post}}/publish?user[id]={{first_post_user}}

###

PATCH http://{{host}}/api/posts/{{first_post}}/like?user[id]={{first_post_user}}
